### ISSUE TITLE
Implementace zrušení publikace obohacovaného objektu z K+ do Feederu

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/DL4DH-Feeder#11]

**Comment by motyc** [comment]
O test prosím @daliboris

**Comment by daliboris** [comment]
Testovací prostředí: 

Kramerius+: 1.0.2

DL4DH Feeder: 1.2.0

Zrušení publikování pomocí  tlačítka v horní ovládací části dopadne v pořádku.

Když je publikace publikovaná, zobrazuje se v seznamu publikací (`/publications`) ve sloupci `Publikováno` zaškrtnutí, ale v ovládacích nabídkách je popisek `Publikovat`, což je zavádějící. **Mělo by tam být** `Zrušit publikaci` a měla by tomu odpovídat i akce po kliknutí na tlačítko. (Nyní se po kliknutí na tlačítko `Publikovat` se objeví zpráva `Položka byla úspěšně publikována`.)

![prostředí pro publikováníé](https://github.com/LIBCAS/DL4DH-Feeder/assets/8056045/2f53c6c3-b4c8-4445-8c6d-e053590ad3ed)

**Comment by sekanIQ** [comment]
Jednalo sa o problém v Kramerius+, ale po zmene vizuálu sa už tento problém neobjavuje.

**Comment by daliboris** [comment]
Opraveno
