### ISSUE TITLE
Problémy ve filtru bibliografických dat

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#12]
V rámci K+ jsem pro Feeder publikoval několik dokumentů (knih, jejichž autorem je Zikmund Winter).

Publikované knihy se zobrazí mezi knihami (po odfiltrování obohacených publikací, tj. `/search?availability=PUBLIC&enrichment=ENRICHED&models=monograph`).

Filtr bibliografických metadat (např. Autor, Rok vydání, Typ dokumentu) obsahují ale pouze hodnoty (a počty), jako by tam byla pouze jedna publikace (Besedy a dumy Vajanského).

Nelze zadat vlastní číslo pro datum vydání, např. 1900 až 1930, abych odfiltroval Vajanského), ve filtru se po přesunu na jiné pole nastaví rok 1884.

**Comment by sekanIQ** [comment]
V  aktuálnej verzií sa daný problém neprejavuje, prosíme o kontrolu, či je momentálne všetko tak, ako má byť. Ďakujem,

**Comment by sekanIQ** [comment]
Opravená filtrácia rokov. Predtým nebolo možné zadať filter mimo min max hodnôt, ktoré sa počítali z vyfiltrovaných publikácií. Teraz už takéto chovanie je možné.

**Comment by daliboris** [comment]
Opraveno.
