### ISSUE TITLE
Abecední řazení položek ve fasetách obohacených dokumentů

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#13]
Položky ve fasetách z obohacujících polí (zeměpisné názvy, instituce ap.) mají neobvyklé/mechanické řazení: velká písmena, malá písmena, diakritika.

Položky by měly být seřazeny podle pravidel českého abecedních řazení.

**Comment by motyc** [comment]
To už je myslím, opraveno... k zavření?
