### ISSUE TITLE
Položky v seznamu vyfiltrovaných publikací není možné vybrat všechny pomocí zaškrtávacího pole v hlavičce seznamu

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#14]
![image](https://user-images.githubusercontent.com/8056045/195590289-0eed149b-1485-4924-b4e9-c9c70a50b919.png)

Po kliknutí na políčko v hlavičce se nic neděje. Očekával bych výběr/zrušení výběru v jednotlivých řádcích tabulky.

**Comment by sekanIQ** [comment]
Hlavné tlačidlo na zaškrtávanie všetkých zorbazených publikácií bolo opravené.
