### ISSUE TITLE
Hledání s pomocí Hledat NameTag a filtru nic nenajde

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#15]
- Vyfiltruju si veřejné publikace, jejichž autorem je Zikmund Winter.
- V poli `Hledat NameTag` zadám výraz `Adam`.
- Z nabídky `Osobní jména` vyberu položku `Adam`.
- Výsledky hledání nevracejí žádné výsledky.

Viz `/search?availability=PUBLIC&authors=Winter%2C+Zikmund&nameTagFacet=Adam&NT=GAAdam`

Pokud z nabídky `Osobní jména` položku `Adam` vyberu rovnou (bez hledání v `Hledat NameTag`), relevantní publikace se najdou.

Viz `/search?availability=PUBLIC&authors=Winter%2C+Zikmund&NT=GAAdam`

**Comment by sekanIQ** [comment]
Filter opravený, aktuálne zobrazuje 10 publikácie pre dotaz `/search?availability=PUBLIC&authors=Winter%2C+Zikmund&nameTagFacet=Adam&NT=GAAdam` rovnako ako pre dotaz `/search?availability=PUBLIC&authors=Winter%2C+Zikmund&NT=GAAdam`.
