### ISSUE TITLE
V tabulkovém zobrazení chybí informace o obohacení publikace

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#16]
Když si zobrazím seznam vyhledaných/vyfiltrovaných publikací v podobě tabulky, nepoznám, která publikace je obohacená a která ne.

![image](https://user-images.githubusercontent.com/8056045/195799251-55fb1558-ba27-4a99-bc37-2002d4687ca7.png)

Navrhuju přidat sloupec `Obohacená` se zaškrtávacím polem (hodnotami ano/ne).

**Comment by sekanIQ** [comment]
Doplnený stĺpec do tabuľky:
![image](https://user-images.githubusercontent.com/99037202/203743613-03c8fb6b-2c10-463b-b49b-818ca8384f96.png)
