### ISSUE TITLE
Ikony pro zoomování obrázku stránky nefungují

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#2]
### Postup

- zobrazím si stránku publikace (např. `/view/uuid:df196150-64dd-11e4-b42a-005056827e52?page=uuid%3A68333e90-694b-11e4-8c6e-001018b5eb5c`
- ve spodní liště, která se zobrazí nad stránkou, kliknu na ikonu s lupou (s + i -)

### Výsledek

- nic se nestane

### Očekávaný výsledek

- stránka se přiblíží nebo oddálí

### Poznámky

- ostatní ikony na liště fungují správně

**Comment by sekanIQ** [comment]
Funkčnosť ikon bola opravená.
