### ISSUE TITLE
Ladění - facety

### ISSUE THREAD

**Issue by motyc** [LIBCAS/DL4DH-Feeder#23]
- [x] Volba „Dostupnost“ -> „Vše“ je pro Feeder nadbytečná (stačí nemít žádný filtr); v Krameriu se to chovalo trošku jinak, proto tam asi byla
- [ ] Jde nějak filtrovat publikace, které (ne)mají ALTO? Pokud ne, měli bychom filtr doplnit.
od @sekanIQ 
> NIE V Solru Krameria sme nenašli príznak, ktorý by vravel, či publikácia obsahuje ALTO a tak nie sme schopný filtrovať podľa takéhoto kritéria.

K druhému bodu bude třeba rozmyslet, jak to řešit, protože pro filtraci by to byl hodně užitečný údaj. Navíc to ovlivňuje i některé funkce a jejich případnou dostupnost.

**Comment by sekanIQ** [comment]
Stále platí, že nie je možné zistiť filtrom, či majú dané publikácie ALTO alebo nie. Potrebné je dotazovať sa postupne na jednotlivé publikácií, čo nie je efektívne. Realizovali sme ale pomocný nástroj, ktorý pred exportom umožní sa dotázať, či všetky publikácie majú ALTO alebo nie. 
![image](https://user-images.githubusercontent.com/99037202/224000705-8fba8836-9914-4490-8ea9-04becf6815d6.png)

**Comment by motyc** [comment]
@sekanIQ Funguje to celkem dobře až na to, že seznam publikací bez ALTO není úplně srozumitelný, nejde nijak snadno dané publikace z výběru odebrat a nejde se podívat ani na jejich detail. Navíc asi bude dělat problémy, pokud by takových publikací bylo v exportu mnoho.

Napadá mne, zda by kontrola na ALTO nemohla být součástí již základního rozhraní, jako tlačítko "Ověřit ALTO" ve výběru publikací pro export. To by umožnilo snadno tyto publikace označit v rámci rozhraní (což je přehlednější než stávající řešení přes combo-box). Teoreticky by to tak mohlo fungovat i tak, že by uživatel klikl na "Ověřit ALTO" v záhlaví stránky, dostal by modal se seznamem publikací s chybějícím ALTO a tam by pak byla volba "Odebrat publikace z exportu", přičemž ta by jen u daných publikací zrušila zaškrtnutí na této stránce:
![image](https://user-images.githubusercontent.com/20186892/228556169-cab659d5-0ae5-4376-881a-b3d6a8887f35.png)

Pro uživatele by to bylo mnohem jasnější a přehlednější, než když je to skryté až v kroku s exportem.

**Comment by sekanIQ** [comment]
Funkcionalita Ověřit ALTO je zložitá a náročná, nakoľko SOLR Krameria neobsahuje túto informáciu a musíme sa pracne dotazovať na každú publikáciu zvlášť, či má ALTO stream alebo nie. Preto neodporúčame túto funkcionalitu rozširovať/propagovať, lebo bude mať negatívny vplyv na výkon Feederu aj Krameria, na ktorý je Feeder napojený.

Funkcionalita, ktorá by zobrazila po overení zoznam publikácií bez ALTO s možnosťou ich vylúčiť z exportu vnímame ako rozvoj.
