### ISSUE TITLE
Ladění - přehled výsledků filtrace

### ISSUE THREAD

**Issue by motyc** [LIBCAS/DL4DH-Feeder#24]
- [ ] Přidat možnost přejít na konkrétní list? (pomohlo by i v základním Krameriu)
- [x] V zobrazení typu Graf je zbytečná volba „Řazení“ na druhém řádku – spíše to mate, protože na výsledky nemá vliv
- [x] Po úpravě způsobu výběru publikací k exportu by se neměly checkboxy v tabulkovém zobrazení zobrazovat, dokud nekliknu na „Exportovat“ – sjednotí se to z dlaždicemi a nebude to mást (navíc související funkce přiskočí až po kliku na Exportovat)

**Comment by sekanIQ** [comment]
Prvy bod bude riešená v rámci issue #47 pri práci s jednotlívými stránkami
