### ISSUE TITLE
Ladění - detail

### ISSUE THREAD

**Issue by motyc** [LIBCAS/DL4DH-Feeder#27]
- [x] https://feeder.nkp.cz/multiview/uuid:df196150-64dd-11e4-b42a-005056827e52/uuid:df196150-64dd-11e4-b42a-005056827e52?page2=uuid%3A677e4670-694b-11e4-8c6e-001018b5eb5c&page=uuid%3A67be83c0-694b-11e4-8c6e-001018b5eb5c – chyba pozicování – levá stránka je částečně schovaná za levým menu a celkově je rozložení chybné (vpravo je to ok)
- [x] ve volbě "Vyhledávání v množině záznamů" se vůbec nedá zohlednit předchozí filtrace, tj. musím tam vše hledat úplně znovu
- [x] údaje v "Detail záznamu" jsou v jiném pořadí než v Krameriu - to jen mate uživatele, sjednotit
- [x] Chybí funkce "Citace", která je v Krameriu - neměla by se také přenést?
- [x] Jak se u publikací bez ALTO bude chovat nástroj pro výběr textu na stránce?
Od @sekanIQ 
> Pokiaľ nie je ALTO, nemáme informáciu o tom, kde na stránke sa nachádza aký text, preto nie sme schopný nijako zabezpečiť funkiu výberu textu ma stránke.

To je mi jasné, ale asi by tedy v takovém případě nástroj neměl být dostupný (zda stránka má ALTO asi půjde celkem snadno zkontrolovat).

- [x] Byla doplněna funkce pro přechod zpět na výsledky filtrace, což je skvělé. Nyní se ale nejde nijak (kromě úpravy URL) dostat na úvodní stránku, protože přes popisek Feederu se vracím zpět na vyhledávání – asi bych funkci přiřadil jinam (samostatné tlačítko v detailu) a chování záhlaví zachoval podle Krameria (tj. návrat na homepage).

**Hledat na stránkách**
- [ ] Nezvýrazní se pozice výrazu na stránce, pokud není přesně v zadané podobě (ale je mezi výsledky)
- [x] Našeptávač se někdy nezobrazí. Moc jsem nedokázal vypozorovat pravidlo, kdy k tomu dojde.
- [x] Pokud stránky (nyní jedné publikace) nejsou obohacené, nemá myslím smysl dávat možnost hledat podle položek NameTag – neměla by se volba skrýt?

**Comment by sekanIQ** [comment]
Bode 1 až 6 opravené/doplnené na DEV prostredí vo verzií 1.4.0. Posledný bod je duplicitný a bude riešený v rámci issue https://github.com/LIBCAS/DL4DH-Feeder/issues/45
