### ISSUE TITLE
Tlačítka pro přiblížení a oddálení stránky jsou schovaná pod šipkou

### ISSUE THREAD

**Issue by daliboris** [LIBCAS/DL4DH-Feeder#3]
### Postup

- zobrazím si stránku publikace (např. `/view/uuid:df196150-64dd-11e4-b42a-005056827e52?page=uuid%3A68333e90-694b-11e4-8c6e-001018b5eb5c`)
- zobrazím si obrázek na celou stránku (pomocí tlačítka na spodní liště k obrázku)

### Výsledek

- v základním zobrazení stránky jsou pod šipkou u postranní lišty schovaná tlačítka pro přiblížení a oddálení obrázku (s ikonami + a -)
![Ikony pod šipkou](https://user-images.githubusercontent.com/8056045/177760710-e0b95d71-1ff7-43f3-a32e-08fb92481db6.png)

- při zobrazení obrázku na celou stránku jsou tlačítka pro přiblížení a oddálení obrázku (s ikonami + a -) zřetelně vidět
![Ikony přes celou stránku](https://user-images.githubusercontent.com/8056045/177760885-a6f00649-89dc-4073-a55b-7782302945a7.png)

### Očekávaný výsledek

-  tlačítka pro přiblížení a oddálení obrázku by v základním zobrazení stránky neměla být vidět, k zoomování slouží tlačítka na spodní liště u obrázku

**Comment by sekanIQ** [comment]
Tlačidlá pre priblíženie boli odstránenie spod šípky. Funkčné zostávajú len tlačidlá v spodnej lište.
