### ISSUE TITLE
Problémy se session

### ISSUE THREAD

**Issue by motyc** [LIBCAS/DL4DH-Feeder#30]
Po přihlášení do aplikace se aplikace po chvíli začala tvářit, že jsem se odhlásil, ale po kliknutí na "přihlásit" došlo k přihlášení bez přechodu na přihlašovací obrazovku. Export ale přesto nešel a naopak došlo jakoby k odhlášení na pozadí, přičemž takto šlo proces opakovat stále dokola a v daném prohlížeči (Firefox) to nešlo vyřešit. Pomohlo až otevření jiného prohlížeče.

**Comment by sekanIQ** [comment]
Nie je možné zreprodukovať, pravdepodovne opravené skôr.
