### ISSUE TITLE
Problém hromadného obohacení externě

### ISSUE THREAD

**Issue by motyc** [LIBCAS/DL4DH-Feeder#31]
Připravit podporu pro workflow, kdy bude třeba hromadně obohatit velké množství dokumentů. Bylo by vhodné mít možnost exportovat data v potřebném formátu z K+ jako vstup pro LINDAT a následně být schopni obohacená data ve známém formátu vrátit zpět do systému.

**Comment by StastnyP** [comment]
Přesunuto pod K+
