### ISSUE TITLE
Při výběru pro export chybí funkce Přidat vše

### ISSUE THREAD

**Issue by motyc** [LIBCAS/DL4DH-Feeder#46]
Mám možnost přidat všechny zobrazené na daném listu, ale není žádná možnost jak přidat do exportu vše napříč listy.

![image](https://user-images.githubusercontent.com/20186892/228557509-dd399da3-cd6b-40d6-be94-362577dbbce1.png)

**Comment by sekanIQ** [comment]
Riešené bude v ramci issue #34
