### ISSUE TITLE
Úvodní strana - vyhledávání

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/DL4DH-Feeder#5]
Jak by mělo fungovat vyhledávání na úvodní straně? Máme implementován našeptávač, po vyhledání již zobrazit výsledky v aplikaci?

**Comment by motyc** [comment]
Mně to přijde logické přesně tak, jak říkáte. Tedy aby se pole chovalo jako to horní pole v hlavním zobrazení a aby se výsledky zobrazily již ve standardním rozhraní...
