### ISSUE TITLE
Implementace negativních filtrů

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/DL4DH-Feeder#9]

**Comment by motyc** [comment]
Mám pocit, že to nějak nefunguje. Když zadám: https://feeder.nkp.cz/search?NT=BBAfrika, nic to nevyhledá. Mělo by to přitom vrátit všechny obohacené publikace, kde není Afrika zmíněna... Nebo je v tom jiná logika?

**Comment by sekanIQ** [comment]
Negatívne filtry opravené.
